name: build-tag-push

on:
  schedule:
    # At 00:00 on Sunday.
    - cron: '0 0 * * 0'
  push:
    branches:
      - main

env:
  TEST_TAG: pipech/erpnext-docker-debian:v15-py3-latest

jobs:
  build-tag-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.6]
        app_branch: [version-15]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Tag and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.LATEST_TAG }}
